#pragma once
// GENERATED by tools/gen_town_goods.py from tools/goods.py - do not edit.
// After a change to goods.py run `py -3 -B tools/gen_town_goods.py` and
// rebuild the plugin; tests/test_town_goods_header.py fails until then.
//
// The goods the town trades (0.9): what a town delivery (a worker delivery
// whose id starts with worker_town_) may make, each as native stacks through
// the game's own ground-drop routine with a {o, b, j:0, c:0} definition.

namespace AfkExpedition {

constexpr int kTownGoodCount = 226;

inline bool TownGood(int type, int id)
{
    switch (type) {
    case 12:  // keys: 27 goods
        return (id >= 0 && id <= 2) || (id >= 7 && id <= 19) || (id >= 21 && id <= 30) || id == 33;
    case 13:  // fragments, shards and tarot cards: 29 goods
        return (id >= 0 && id <= 1) || (id >= 18 && id <= 42) || (id >= 54 && id <= 55);
    case 14:  // materials: 58 goods
        return (id >= 0 && id <= 23) || (id >= 27 && id <= 39) || (id >= 43 && id <= 44) || (id >= 49 && id <= 51)
            || (id >= 53 && id <= 58) || (id >= 60 && id <= 66) || (id >= 68 && id <= 70);
    case 15:  // runes, gems, jewels and orbs: 112 goods
        return (id >= 1 && id <= 69) || (id >= 78 && id <= 96) || (id >= 112 && id <= 135);
    default:
        return false;
    }
}

}  // namespace AfkExpedition
