'use strict';
// share.js renders a delivered expedition's summary on a canvas. A recording
// 2D context stands in for the browser; nothing is drawn or saved for real.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');

function load(){
  const context=vm.createContext({window:{},console,URL:{createObjectURL:()=>'blob:x',revokeObjectURL(){}},setTimeout(){},
    Image:class{set src(v){this.width=32;this.height=32;setImmediate(()=>v.includes('missing')?this.onerror():this.onload());}},setImmediate});
  vm.runInContext(fs.readFileSync(path.join(__dirname,'../web/share.js'),'utf8'),context);
  return context.window.AfkShare;
}
function canvas(){
  const texts=[],images=[];
  const ctx=new Proxy({texts,images,measureText:t=>({width:String(t).length*8}),fillText(t){texts.push(String(t));},drawImage(i){images.push(i);},
    createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>{o[k]=v;return true;}});
  return {getContext:()=>ctx,ctx};
}
const summary={version:'0.7.0',hero:{name:'Suh',class_name:'Samurai',level_before:88,level_now:90},region:'The Glacial Trail',hours:2.5,
  kills:12345,exp:42728970,gold:33105,items:88,visible_rarities:{Satanic:10,Set:3,Heroic:1},mode:'siege',
  siege:{level:12,waves_fought:27,waves_held:4,fell:true,record:true},delivered_at:'2026-09-24T10:00:00Z',partial:false,
  best:[{name:'Shield of the Abyss',group:'Heroic',icon:'/assets/items/1.png',count:1},{name:'Angel',group:'Satanic',icon:'/assets/items/missing.png',count:3}],
  wishlist_hits:[{name:"Harlequinn's Crest"}],new_finds_total:4};

test('numbers and times are short and readable',()=>{
  const share=load();
  assert.equal(share.short(42728970),'42.7M');assert.equal(share.short(33105),'33.1K');assert.equal(share.short(88),'88');assert.equal(share.short(null),'—');
  assert.equal(share.hours(0.25),'15 min');assert.equal(share.hours(2.5),'2 h 30 min');assert.equal(share.hours(8),'8 h');
  assert.deepEqual({...share.lines(summary)},{title:'Suh',sub:'Level 88 → 90 · Samurai · The Glacial Trail · 2 h 30 min'});
});

test('the card shows the hero, the siege result, the drops and wishlist finds',async()=>{
  const share=load(),c=canvas();await share.draw(summary,c);
  const text=c.ctx.texts.join('\n');
  assert.equal(c.width,1200);assert.equal(c.height,630);
  for(const expected of ['Suh','SIEGE L12 · 27 WAVES · FELL · NEW RECORD','42.7M','Shield of the','Abyss','Heroic 1','★ Wishlist: Harlequinn\'s Crest','+4 new collection entries','×3'])
    assert.ok(text.includes(expected),`missing: ${expected}`);
  assert.equal(c.ctx.images.length,1,'a missing icon is skipped, never drawn broken');
  assert.match(text,/generated by the game's own drop calls/);
  assert.doesNotMatch(text,/· 4 WAVES/,'the badge counts the waves fought, not the waves fully held (MEASURED 2026-09-24: "0 WAVES" after 6)');
});

test('a partial farm delivery says so and shows no siege badge',async()=>{
  const share=load(),c=canvas();await share.draw({...summary,mode:'farm',siege:null,partial:true,wishlist_hits:[],new_finds_total:0},c);
  const text=c.ctx.texts.join('\n');
  assert.match(text,/\(partial\)/);assert.doesNotMatch(text,/SIEGE L/);assert.doesNotMatch(text,/Wishlist/);
});
