"""Write plugin/include/AfkExpedition/TownGoods.hpp from tools/goods.py (0.9).

A town delivery (a worker delivery whose id starts with ``worker_town_``) may
make exactly the goods the town trades: the keys of ``goods.GOODS``. This
script turns that list into the C++ function ``TownGood(type, id)``, so the
list lives in one place.

    py -3 -B tools/gen_town_goods.py            write the header
    py -3 -B tools/gen_town_goods.py --check    exit 1 when it is out of date

tests/test_town_goods_header.py fails while the header is out of date. The
plugin DLL carries its own copy of the list: rebuild it after a change.

Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
HEADER = ROOT / 'plugin' / 'include' / 'AfkExpedition' / 'TownGoods.hpp'

sys.path.insert(0, str(HERE))
import goods  # noqa: E402  (tools/ is a folder of scripts, not a package)

_KEY = re.compile(r'(\d+):(\d+)')
# The plugin makes every good as native stacks with a {o, b, j:0, c:0}
# definition, which only fits the stackable item types.
STACKABLE_TYPES = {12: 'keys', 13: 'fragments, shards and tarot cards', 14: 'materials', 15: 'runes, gems, jewels and orbs'}
# Addresses in those types that the game keeps as single items, never stacks
# (the Item Editor's MATERIAL_SINGLETON_ADDRESSES).
SINGLE_ITEMS = frozenset({*((13, base) for base in range(58, 65)), (14, 59), (14, 67)})


def goods_by_type(table: dict | None = None) -> dict[int, list[int]]:
    """The goods' ids by item type, both ascending. Refuses a key that is not
    ``type:id``, a type that is not a native stackable and a single item."""
    table = goods.GOODS if table is None else table
    by: dict[int, set[int]] = {}
    for key in table:
        match = _KEY.fullmatch(str(key))
        if not match:
            raise ValueError(f'Good {key!r} is not keyed "type:id".')
        item_type, item_id = int(match.group(1)), int(match.group(2))
        if item_type not in STACKABLE_TYPES:
            raise ValueError(f'Good {key} is not a native stackable (item types 12-15).')
        if (item_type, item_id) in SINGLE_ITEMS:
            raise ValueError(f'Good {key} is a single item in the game, never a stack.')
        by.setdefault(item_type, set()).add(item_id)
    if not by:
        raise ValueError('No goods to write.')
    return {item_type: sorted(ids) for item_type, ids in sorted(by.items())}


def ranges(ids) -> list[tuple[int, int]]:
    """Consecutive ids as (first, last) pairs, ascending."""
    out: list[list[int]] = []
    for i in sorted(set(ids)):
        if out and i == out[-1][1] + 1:
            out[-1][1] = i
        else:
            out.append([i, i])
    return [(first, last) for first, last in out]


def _term(first: int, last: int) -> str:
    return f'id == {first}' if first == last else f'(id >= {first} && id <= {last})'


def render(table: dict | None = None) -> str:
    """The header's text, LF line endings."""
    by = goods_by_type(table)
    count = sum(len(ids) for ids in by.values())
    lines = [
        '#pragma once',
        '// GENERATED by tools/gen_town_goods.py from tools/goods.py - do not edit.',
        '// After a change to goods.py run `py -3 -B tools/gen_town_goods.py` and',
        '// rebuild the plugin; tests/test_town_goods_header.py fails until then.',
        '//',
        '// The goods the town trades (0.9): what a town delivery (a worker delivery',
        '// whose id starts with worker_town_) may make, each as native stacks through',
        "// the game's own ground-drop routine with a {o, b, j:0, c:0} definition.",
        '',
        'namespace AfkExpedition {',
        '',
        f'constexpr int kTownGoodCount = {count};',
        '',
        'inline bool TownGood(int type, int id)',
        '{',
        '    switch (type) {',
    ]
    for item_type, ids in by.items():
        terms = [_term(first, last) for first, last in ranges(ids)]
        rows = [' || '.join(terms[i:i + 4]) for i in range(0, len(terms), 4)]
        lines.append(f'    case {item_type}:  // {STACKABLE_TYPES[item_type]}: {len(ids)} goods')
        lines.append(f'        return {rows[0]}' + ('' if len(rows) > 1 else ';'))
        for n, row in enumerate(rows[1:], start=2):
            lines.append(f'            || {row}' + (';' if n == len(rows) else ''))
    lines += [
        '    default:',
        '        return false;',
        '    }',
        '}',
        '',
        '}  // namespace AfkExpedition',
        '',
    ]
    return '\n'.join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description='Write the TownGood(type, id) header from tools/goods.py.')
    ap.add_argument('--check', action='store_true', help='only tell whether the header is up to date (exit 1 when it is not)')
    args = ap.parse_args(argv)
    text = render()
    count = sum(len(ids) for ids in goods_by_type().values())
    name = HEADER.relative_to(ROOT).as_posix()
    current = HEADER.read_text(encoding='utf-8') if HEADER.exists() else None
    if current == text:
        print(f'{name} is up to date ({count} goods).')
        return 0
    if args.check:
        print(f'{name} is out of date: run py -3 -B tools/gen_town_goods.py', file=sys.stderr)
        return 1
    HEADER.write_text(text, encoding='utf-8', newline='\n')
    print(f'Wrote {name} ({count} goods).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
